baseURL = 'https://example.com/'
languageCode = 'en-us'
title = "valenvilardav"
copyright = 'Valentin Vilar Davila' # Used in the footer copyright mention.
enableRobotsTXT = true

[Languages]
  [Languages.es]
    languageName = "Español"
    weight = 1
    languageCode = "es"   
    contentDir = "content/es"

  [Languages.en]
    languageName = "English"
    weight = 2
    languageCode = "en-us"   
    contentDir = "content/en"

defaultContentLanguage = "es"

[module]
  [[module.imports]]
    path = "github.com/michenriksen/hugo-theme-til"

[params.author]
    name = 'Valentin Vilar Davila'
    email = 'valentinvilardavila@gmail.com'

[params.home]
    showRecentPosts = true

    recentPostsLimit = 3

    showRecentNotes = true

    recentNotesLimit = 5

  [params.notes]
    pageSize = 20

    showCategoryFilter = true

  [params.footer]
    creativeCommonsLicense = 'none'

    showCreativeCommonsIcons = true

    showThemeCredit = true

  [params.robotstxt]
    blockCC = false

    blockAI = false

[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']

[menus]
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 20
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 30
  [[menus.main]]
    name = 'Graph'
    pageRef = '/graph'
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false
    style = 'tokyonight-night'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true